language: php
branches:
  only:
  - dev
notifications:
  email:
    on_success: never
    on_failure: change
php:
- 7.1
- 7.2
env:
- WP_VERSION=latest WP_MULTISITE=1
before_install:
- composer install --dev
before_script:
- if php -v | grep -q 'Xdebug'; then phpenv config-rm xdebug.ini; fi
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
